appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: JbqxOtVyfztRGQHtppJGTTmxnQBsxsCBwZQSK7IF59gkVU7KGYXkT10XAKoritGbnMVDZsItGxpAWWKMQfLOaS/0Mad8tSORUL/nujCvQtuX68AbXDHvj7mbvOtVXgwlQzRc/F16v0L13F0kCJmRVw29I+S05qDv3pTAYPWd9DX98msRz3ztNKXDUtQlAoF3/3U/4lhK81r8ymUcXXNmDEtW8gIzkQrlJssMtE8QpkKmTHFLnWszOhEu8bayRF7027SiMBgdReUgaG6+5cfHJa1YlsZCWtryI8NfJhl5vj1RFfqGu+tkgVsHUSJwrlhFH2OlOV3KE8bsLN3NGgBvRUfsEb8sXCPhcYAD/UtULWgqFt1k+37S+dw12hyniMFcPPbiY2axVaF71OlgtxJd78AWlnXZNc4sbgv0B0kyBtnyH3/WqRPqcdw+FqcJqKvLtXIQuiUEF8vmOXGEAyqvtOf8ffk2EdYFVT1WpCLz5E/8JshaizWrWjta9Z1BzilU+4HgdrJXf/Vwhgk/2e6DNq6D3fdGoTbmoKzUMHEjUJ68uXHHIsc4x42Qd5vEWFSLEQr9SwFZscUm1xyrd0io7lgTdPl/lmeQDhSF2dlxsOS8GOocIztrfX9droAA4HMLfSn4bnnP/9Y8hzMsbrvktwoHFrSOFLZyUhmiWR1V3bs=}
